TEMPLATEFILE=../templates/cluster_init.yaml
RESULT=cluster.yaml

rm -f ${RESULT}*

LBDNSNAME=${1:-THIS_NEEDS_THE_LOAD_BALANCER_DNS_NAME}
CLUSTERNAME=${2:-THIS_NEEDS_THE_CLUSTERNAME}

cat ${TEMPLATEFILE} | sed "s|LBNAME|${LBDNSNAME}|g" | sed "s|CLUSTERNAME|${CLUSTERNAME}|g" > $RESULT

